SELECT * FROM BOARD;
SELECT * FROM MEMBER;
DROP TABLE MEMBER;
DROP TABLE BOARD;
select * from all_tables;

CREATE TABLE MEMBER(
	MEMNUM INT PRIMARY KEY,
	NAME VARCHAR(15),
	MID VARCHAR(15),
	MPW VARCHAR(15)
);

CREATE TABLE BOARD(
	BORNUM INT PRIMARY KEY,
	CONTENT VARCHAR(300),
	TITLE VARCHAR(50),
	WRITER VARCHAR(20)
);
INSERT INTO BOARD VALUES((SELECT NVL(MAX(BORNUM), 0)+1 FROM BOARD),'돌아가줘','제발요','kim')
INSERT INTO MEMBER VALUES (1, '김영진','kim','1234');
SELECT * FROM BOARD WHERE TITLE LIKE '%' ORDER BY BORNUM DESC;
SELECT * FROM BOARD WHERE TITLE LIKE '%' ORDER BY BORNUM DESC;
INSERT INTO BOARD VALUES(1, '돌아자','제발 멈춰','kim');
INSERT INTO BOARD VALUES(2, '기이다','제 해주세요','kim');
INSERT INTO BOARD VALUES(3, '제','제발 춰','jin');
INSERT INTO BOARD VALUES(4, '돌려','돌리자','jin');
select * from all_tables;