SELECT * FROM ALL_TABLES;

CREATE TABLE BOARD2(
	ID INT PRIMARY KEY,
	TITLE VARCHAR(30),
	WRITER VARCHAR(15),
	CONTENT VARCHAR(100),
	WDATE DATE DEFAULT SYSDATE
);

CREATE TABLE MEMBER2(
	ID VARCHAR(15) PRIMARY KEY,
	PASSWORD VARCHAR(15),
	NAME VARCHAR(15),
	ROLE VARCHAR(15)

);

select * from board2;
select * from member2;


INSERT INTO MEMBER2 VALUES('kim', '1234', '辫揪', 'USER');
INSERT INTO MEMBER2 VALUES('admin', '1234', '包府磊', 'ADMIN');

INSERT INTO BOARD2(ID, TITLE, WRITER, CONTENT) VALUES(1, '力格','kim', '臂郴侩');







